"""added forgeinkey

Revision ID: 846aadce1597
Revises: 4bbe7c634679
Create Date: 2024-04-11 10:09:53.545819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846aadce1597'
down_revision: Union[str, None] = '4bbe7c634679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Todo', sa.Column('auther_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Todo', 'User', ['auther_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Todo', type_='foreignkey')
    op.drop_column('Todo', 'auther_id')
    # ### end Alembic commands ###
